apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernates.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /posts
            backend:
              serviceName: posts-clusterip-service
              servicePort: 4000
          - path: /query
            backend:
              serviceName: query-clusterip-service
              servicePort: 4002
          - path: /posts/.*/comments
            backend:
              serviceName: comments-clusterip-service
              servicePort: 4001
          - path: /.*
            backend:
              serviceName: client-clusterip-service
              servicePort: 3000
